import { NextResponse } from 'next/server';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { formatINR } from '@/lib/utils';

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);

  const buyerName = searchParams.get('buyer_name') ?? 'Unknown buyer';
  const plotLabel = searchParams.get('plot_label') ?? 'Plot TBD';
  const projectName = searchParams.get('project_name') ?? 'X7 WhatsAI Offer';
  const tokenAmount = Number(searchParams.get('token_amount') ?? 0);
  const totalAmount = Number(searchParams.get('total_amount') ?? 0);
  const paymentMode = (searchParams.get('payment_mode') ?? 'UPI').toUpperCase();
  const bookingDate = searchParams.get('booking_date') ?? new Date().toISOString();
  const status = (searchParams.get('status') ?? 'token_paid').replace(/_/g, ' ');
  const tokenText = formatINR(tokenAmount, { compact: false }).replace('₹', 'INR ');
  const totalText = formatINR(totalAmount, { compact: false }).replace('₹', 'INR ');

  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawRectangle({
    x: 40,
    y: 760,
    width: 515,
    height: 54,
    color: rgb(0.06, 0.09, 0.16),
  });

  page.drawText('X7 WhatsAI Assistant', {
    x: 56,
    y: 792,
    size: 20,
    font: bold,
    color: rgb(1, 1, 1),
  });
  page.drawText('Booking Receipt', {
    x: 56,
    y: 772,
    size: 11,
    font,
    color: rgb(0.85, 0.88, 0.93),
  });

  const rows = [
    ['Project', projectName],
    ['Buyer', buyerName],
    ['Plot', plotLabel],
    ['Booking date', new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(bookingDate))],
    ['Payment mode', paymentMode],
    ['Status', status],
    ['Token amount', tokenText],
    ['Total amount', totalText],
  ];

  let y = 714;
  for (const [label, value] of rows) {
    page.drawText(label, {
      x: 56,
      y,
      size: 11,
      font: bold,
      color: rgb(0.28, 0.33, 0.38),
    });
    page.drawText(String(value), {
      x: 180,
      y,
      size: 11,
      font,
      color: rgb(0.1, 0.12, 0.16),
    });
    y -= 34;
  }

  page.drawLine({
    start: { x: 56, y: y + 8 },
    end: { x: 539, y: y + 8 },
    thickness: 1,
    color: rgb(0.86, 0.89, 0.93),
  });

  page.drawText('Receipt Summary', {
    x: 56,
    y: y - 22,
    size: 13,
    font: bold,
    color: rgb(0.06, 0.09, 0.16),
  });

  page.drawText(
    `${buyerName} has initiated a ${status} booking for plot ${plotLabel} in ${projectName}. This receipt can be shared with the buyer over WhatsApp while the agreement package is being prepared.`,
    {
      x: 56,
      y: y - 50,
      size: 11,
      font,
      color: rgb(0.16, 0.2, 0.24),
      lineHeight: 16,
      maxWidth: 483,
    },
  );

  page.drawText('Generated by Project NEEV Sales Engine', {
    x: 56,
    y: 72,
    size: 10,
    font,
    color: rgb(0.45, 0.5, 0.57),
  });

  const bytes = await pdf.save();
  const filename = `booking-receipt-${plotLabel.toLowerCase().replace(/\s+/g, '-')}.pdf`;

  return new NextResponse(Buffer.from(bytes), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `inline; filename="${filename}"`,
      'Cache-Control': 'no-store',
    },
  });
}
