'use client';

import { useMemo, useRef, useState } from 'react';
import { AlertTriangle, CheckCircle2, FileText, ImageIcon, MessageCircleReply, Paperclip, Plus, Search, Trash2, Upload, Video, X } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { hasTemplatePlaceholder, matchKeywordReply } from '@/lib/keyword-reply-schema';
import type { KeywordReplyRule } from '@/types/database';

type Props = { rules: KeywordReplyRule[]; fallbackReply: string; businessId?: string | null; playbookId?: string | null; onRulesChange: (rules: KeywordReplyRule[]) => void; onFallbackReplyChange: (value: string) => void };

export function KeywordReplyEditor({ rules, fallbackReply, businessId, playbookId, onRulesChange, onFallbackReplyChange }: Props) {
  const [testMessage, setTestMessage] = useState('');
  const match = useMemo(() => matchKeywordReply(testMessage, rules), [rules, testMessage]);
  const incompleteRules = useMemo(() => rules.filter((rule) => !rule.reply.trim() || hasTemplatePlaceholder(rule.reply)), [rules]);
  const incompleteCount = incompleteRules.length + (hasTemplatePlaceholder(fallbackReply) ? 1 : 0);
  const updateRule = (id: string, patch: Partial<KeywordReplyRule>) => onRulesChange(rules.map((rule) => rule.id === id ? { ...rule, ...patch } : rule));
  const addRule = () => { const suffix = rules.length + 1; onRulesChange([...rules, { id: uniqueId(`reply-${suffix}`, rules), label: `Reply ${suffix}`, keywords: [], match_type: 'word', reply: '', priority: Math.max(0, 100 - rules.length), enabled: true, handoff: false, fuzzy_enabled: true, fuzzy_threshold: 0.82 }]); };
  return <div className="space-y-5">
    <div className="rounded-3xl border border-[#b7efc5] bg-[#f4fff6] p-5"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-[#00a884] text-white"><MessageCircleReply className="h-5 w-5" /></div><div><h3 className="font-semibold text-[#111b21]">Keywords, exact replies, and attachments</h3><p className="mt-1 text-sm leading-relaxed text-[#667781]">Use the messages customers actually send. WhatsAI handles common Hinglish variants without generated text. Attach JPEG, PNG, MP4, or PDF files after the assistant is first saved.</p></div></div>{incompleteCount > 0 ? <div className="mt-4 flex items-start gap-3 rounded-2xl border border-[#f6cf75] bg-[#fff7df] p-3 text-sm text-[#784f00]"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" /><div><strong>Fill in the blanks: {incompleteCount} response{incompleteCount === 1 ? '' : 's'} still need your business details.</strong><p className="mt-1 text-xs">Replies with brackets cannot be saved or sent. Replace each highlighted value with your real fee, address, timing, or offer.</p></div></div> : <div className="mt-4 flex items-center gap-2 text-sm font-medium text-[#075e54]"><CheckCircle2 className="h-4 w-4" />All replies are ready to save.</div>}</div>
    <div className="space-y-4">{rules.map((rule, index) => <RuleCard key={rule.id} rule={rule} index={index} businessId={businessId} playbookId={playbookId} onChange={(patch) => updateRule(rule.id, patch)} onDelete={() => onRulesChange(rules.filter((item) => item.id !== rule.id))} />)}</div>
    <Button type="button" variant="outline" className="w-full border-dashed border-[#00a884] text-[#075e54] hover:bg-[#e7fce3]" onClick={addRule} disabled={rules.length >= 30}><Plus className="mr-2 h-4 w-4" />Add another reply</Button>
    <div className="grid gap-5 lg:grid-cols-2"><div className="space-y-2"><Label htmlFor="fallback-reply">Fallback reply</Label><Textarea id="fallback-reply" value={fallbackReply} onChange={(event) => onFallbackReplyChange(event.target.value)} rows={5} placeholder="Thanks for your message. Our team will reply shortly." className={hasTemplatePlaceholder(fallbackReply) ? 'border-[#e0a900] bg-[#fffbea] focus-visible:ring-[#e0a900]' : ''} /><p className="text-xs text-muted-foreground">Sent when no rule matches. The conversation is also handed to the owner.</p></div><div className="rounded-3xl border border-[#d8dee4] bg-[#f0f2f5] p-4"><Label htmlFor="keyword-tester" className="flex items-center gap-2"><Search className="h-4 w-4 text-[#00a884]" />Live tester</Label><Input id="keyword-tester" className="mt-3 bg-white" value={testMessage} onChange={(event) => setTestMessage(event.target.value)} placeholder="Try: fees kya hai, kitna lgega, loc bhejo" /><div className="mt-3 min-h-28 rounded-2xl bg-[#efeae2] p-3">{testMessage.trim() ? <div className="ml-auto max-w-[90%] rounded-2xl rounded-tr-sm bg-[#d9fdd3] px-4 py-3 text-sm shadow-sm">{match && hasTemplatePlaceholder(match.reply) ? 'Complete this matching reply before WhatsAI can send it.' : hasTemplatePlaceholder(fallbackReply) && !match ? 'Complete the fallback reply before WhatsAI can send it.' : match?.reply ?? fallbackReply}<div className="mt-2 flex items-center justify-between text-[10px] text-[#667781]"><span>{match ? `Matched: ${match.label}` : 'Fallback reply'}</span><CheckCircle2 className="h-3 w-3" /></div></div> : <p className="p-3 text-center text-xs text-[#667781]">Your matched reply appears here.</p>}</div></div></div>
  </div>;
}

function RuleCard({ rule, index, businessId, playbookId, onChange, onDelete }: { rule: KeywordReplyRule; index: number; businessId?: string | null; playbookId?: string | null; onChange: (patch: Partial<KeywordReplyRule>) => void; onDelete: () => void }) {
  const [keywordDraft, setKeywordDraft] = useState(''); const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState<string | null>(null); const fileInput = useRef<HTMLInputElement>(null); const uploadReady = Boolean(businessId && playbookId);
  const commitKeywords = (raw: string) => { const incoming = raw.split(',').map((value) => value.trim()).filter(Boolean); if (!incoming.length) return; onChange({ keywords: [...new Set([...rule.keywords, ...incoming])].slice(0, 20) }); setKeywordDraft(''); };
  async function upload(file?: File) { if (!file || !businessId || !playbookId) return; setUploadError(null); setUploading(true); try { const form = new FormData(); form.set('business_id', businessId); form.set('playbook_id', playbookId); form.set('rule_id', rule.id); form.set('file', file); const response = await fetch('/api/whatsai/media', { method: 'POST', body: form }); const payload = await response.json(); if (!response.ok || !payload.ok) throw new Error(payload.error || 'Upload failed.'); onChange({ media_asset_id: payload.asset.id, media_storage_path: payload.asset.storage_path, media_type: payload.asset.media_type, media_name: payload.asset.media_name, media_mime_type: payload.asset.media_mime_type, media_size_bytes: payload.asset.media_size_bytes, media_url: payload.asset.preview_url }); } catch (error) { setUploadError(error instanceof Error ? error.message : 'Upload failed.'); } finally { setUploading(false); } }
  async function removeAttachment() { if (rule.media_asset_id) await fetch('/api/whatsai/media', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ asset_id: rule.media_asset_id }) }); onChange({ media_asset_id: undefined, media_storage_path: undefined, media_type: undefined, media_name: undefined, media_mime_type: undefined, media_size_bytes: undefined, media_url: undefined }); }
  const MediaIcon = rule.media_type === 'video' ? Video : rule.media_type === 'image' ? ImageIcon : FileText;
  const incomplete = !rule.reply.trim() || hasTemplatePlaceholder(rule.reply);
  return <div className={`rounded-3xl border bg-white p-4 shadow-sm sm:p-5 ${incomplete ? 'border-[#f0bd42] bg-[#fffdf6]' : 'border-[#d8dee4]'}`}><input ref={fileInput} type="file" className="sr-only" accept="image/jpeg,image/png,video/mp4,application/pdf" onChange={(event) => { void upload(event.target.files?.[0]); event.currentTarget.value = ''; }} />
    <div className="flex items-start justify-between gap-3"><div><div className={`text-xs font-semibold uppercase tracking-wide ${incomplete ? 'text-[#9a6700]' : 'text-[#00a884]'}`}>Rule {index + 1}</div><h4 className="mt-1 font-semibold text-[#111b21]">{rule.label || 'Untitled reply'}</h4>{incomplete ? <div className="mt-2 flex items-center gap-1.5 text-xs font-medium text-[#9a6700]"><AlertTriangle className="h-3.5 w-3.5" />Fill in this reply before setup.</div> : null}</div><Button type="button" variant="ghost" size="icon" onClick={onDelete} aria-label={`Delete ${rule.label}`}><Trash2 className="h-4 w-4 text-red-500" /></Button></div>
    <div className="mt-4 grid gap-4 md:grid-cols-[minmax(0,1fr)_180px]"><div className="space-y-2"><Label>Rule name</Label><Input value={rule.label} onChange={(event) => onChange({ label: event.target.value, ...(rule.media_asset_id ? {} : { id: slugify(event.target.value) || rule.id }) })} placeholder="Fees" /></div><div className="space-y-2"><Label>Match type</Label><Select value={rule.match_type} onValueChange={(value) => onChange({ match_type: value as KeywordReplyRule['match_type'] })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="word">Whole word</SelectItem><SelectItem value="exact">Exact message</SelectItem><SelectItem value="contains">Contains phrase</SelectItem></SelectContent></Select></div></div>
    <div className="mt-4 space-y-2"><Label>Keywords</Label><Input value={keywordDraft} onChange={(event) => setKeywordDraft(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ',') { event.preventDefault(); commitKeywords(keywordDraft); } }} onBlur={() => commitKeywords(keywordDraft)} placeholder="Type a keyword and press Enter" /><div className="flex min-h-7 flex-wrap gap-2">{rule.keywords.map((keyword) => <Badge key={keyword} variant="secondary" className="gap-1 bg-[#e7fce3] text-[#075e54]">{keyword}<button type="button" onClick={() => onChange({ keywords: rule.keywords.filter((item) => item !== keyword) })} aria-label={`Remove ${keyword}`}><X className="h-3 w-3" /></button></Badge>)}</div></div>
    <div className="mt-4 space-y-2"><Label>Exact reply</Label><Textarea value={rule.reply} onChange={(event) => onChange({ reply: event.target.value })} rows={4} placeholder="Our monthly fee is Rs 1,500. Would you like to book a visit?" className={incomplete ? 'border-[#e0a900] bg-[#fffbea] focus-visible:ring-[#e0a900]' : ''} />{incomplete ? <p className="text-xs text-[#9a6700]">Replace all text inside square brackets with your real business details.</p> : null}</div>
    <div className="mt-4 rounded-2xl border border-[#d8dee4] bg-[#f8fafb] p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-sm font-medium text-[#111b21]"><Paperclip className="h-4 w-4 text-[#00a884]" />Automatic attachment</div><p className="mt-1 text-xs text-[#667781]">JPEG, PNG, MP4, or PDF. Maximum 16 MB.</p></div>{rule.media_asset_id ? <Button type="button" variant="outline" size="sm" onClick={() => void removeAttachment()}><X className="mr-1 h-3.5 w-3.5" />Remove</Button> : <Button type="button" variant="outline" size="sm" disabled={!uploadReady || uploading} onClick={() => fileInput.current?.click()}><Upload className="mr-1 h-3.5 w-3.5" />{uploading ? 'Uploading...' : 'Attach file'}</Button>}</div>{rule.media_asset_id && <div className="mt-3 flex items-center gap-2 rounded-xl bg-white p-2 text-sm text-[#075e54]"><MediaIcon className="h-4 w-4" /><span className="min-w-0 flex-1 truncate">{rule.media_name}</span><Badge variant="secondary">{rule.media_type}</Badge></div>}{!uploadReady && <p className="mt-3 text-xs text-[#a15c00]">Save the assistant once, then return to this step to attach a private file.</p>}{uploadError && <p className="mt-3 text-xs text-red-600">{uploadError}</p>}</div>
    <div className="mt-4 flex flex-wrap gap-5 text-sm"><label className="flex cursor-pointer items-center gap-2"><input type="checkbox" checked={rule.enabled} onChange={(event) => onChange({ enabled: event.target.checked })} className="h-4 w-4 accent-[#00a884]" />Active</label><label className="flex cursor-pointer items-center gap-2"><input type="checkbox" checked={rule.fuzzy_enabled !== false} onChange={(event) => onChange({ fuzzy_enabled: event.target.checked })} className="h-4 w-4 accent-[#00a884]" />Catch common Hinglish typos</label><label className="flex cursor-pointer items-center gap-2"><input type="checkbox" checked={rule.handoff} onChange={(event) => onChange({ handoff: event.target.checked })} className="h-4 w-4 accent-[#f59e0b]" />Alert owner after reply</label></div>
  </div>;
}
function slugify(value: string) { return value.toLocaleLowerCase('en-IN').trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60); }
function uniqueId(candidate: string, rules: KeywordReplyRule[]) { let value = candidate; let suffix = 2; while (rules.some((rule) => rule.id === value)) value = `${candidate}-${suffix++}`; return value; }
