import { Phone, MessageCircle, Mail } from 'lucide-react';
import type { LandingProject, LandingBuilder } from '@/lib/types';
export function Footer({ project, builder }: { project: LandingProject; builder: LandingBuilder }) {
  const wa = builder.whatsapp_number?.replace(/[^\d]/g, '');
  return (
    <footer className="px-6 lg:px-12 py-10 bg-slate-950 text-slate-300">
      <div className="max-w-6xl mx-auto grid md:grid-cols-3 gap-8">
        <div><div className="font-semibold text-white">{builder.company_name}</div><p className="mt-2 text-sm">{project.name} — {project.location}</p>{project.rera_number && <p className="mt-2 text-xs opacity-70">Verification: {project.rera_number}</p>}</div>
        <div className="space-y-2 text-sm">
          <div className="font-semibold text-white">Contact</div>
          {builder.phone && <a href={`tel:${builder.phone}`} className="flex items-center gap-2"><Phone className="h-4 w-4" /> {builder.phone}</a>}
          {wa && <a href={`https://wa.me/${wa}`} className="flex items-center gap-2"><MessageCircle className="h-4 w-4" /> WhatsApp</a>}
          {builder.email && <a href={`mailto:${builder.email}`} className="flex items-center gap-2"><Mail className="h-4 w-4" /> {builder.email}</a>}
        </div>
        <div className="text-xs opacity-70"><p>© {new Date().getFullYear()} {builder.company_name}.</p><p className="mt-2">Generated by WhatsAI Assistant.</p></div>
      </div>
    </footer>
  );
}
