import { Sparkles, Plus } from 'lucide-react';
import { PageHeader } from '@/components/shared/PageHeader';
import { Button } from '@/components/ui/button';
import { KPICard } from '@/components/shared/KPICard';
import { ContentBoard } from '@/components/content/ContentBoard';
import { GenerateCalendarDialog } from '@/components/content/GenerateCalendarDialog';
import { loadContentPageData, contentReadSourceLabel } from '@/lib/content-read';

export const metadata = { title: 'Content' };

export default async function ContentPage() {
  const { entries, stats, source } = await loadContentPageData();

  return (
    <>
      <PageHeader
        title="Content Calendar"
        titleHi="कंटेंट कैलेंडर"
        description="60+ posts, reels, and ads per month — generated by GPT-4o + Remotion + Higgsfield."
        actions={
          <>
            <GenerateCalendarDialog />
            <Button size="sm"><Plus className="h-4 w-4 mr-2" /> New Post</Button>
          </>
        }
      />
      <p className="mb-6 -mt-3 text-xs text-muted-foreground">{contentReadSourceLabel(source)}</p>

      <section className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
        <KPICard label="Posts This Month"  value={stats.thisMonth}        icon={Sparkles} accent="primary" />
        <KPICard label="Rendered"           value={stats.rendered}         icon={Sparkles} accent="success" />
        <KPICard label="Avg Virality"       value={stats.avgVirality}      icon={Sparkles} accent="warning" />
        <KPICard label="Awaiting Approval"  value={stats.awaitingApproval} icon={Sparkles} accent="primary" />
      </section>

      <ContentBoard entries={entries} />
    </>
  );
}
