import Link from 'next/link';
import { ArrowLeft, ExternalLink, ShieldCheck } from 'lucide-react';
import { WhatsAppConnectionTest } from '@/components/whatsai/WhatsAppConnectionTest';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

export default function WhatsAppConnectionGuidePage() {
  return <div className="mx-auto max-w-3xl space-y-6"><Button variant="ghost" asChild><Link href="/assistant-setup"><ArrowLeft className="mr-2 h-4 w-4" />Back to setup</Link></Button><div><p className="text-sm font-semibold text-[#00a884]">WhatsApp Business Platform</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Connect your WhatsApp number</h1><p className="mt-2 text-muted-foreground">Follow these simple steps once. WhatsAI will then receive and answer your customer messages.</p></div><Card><CardHeader><CardTitle>1. Create or open your Meta app</CardTitle><CardDescription>Use Meta for Developers and add the WhatsApp use case.</CardDescription></CardHeader><CardContent><Button asChild variant="outline"><a href="https://developers.facebook.com/apps/" target="_blank" rel="noreferrer">Open Meta Developers <ExternalLink className="ml-2 h-4 w-4" /></a></Button></CardContent></Card><Card><CardHeader><CardTitle>2. Copy your connection details</CardTitle><CardDescription>In WhatsApp API Setup, copy the Phone Number ID and WhatsApp Business Account ID into the Setup wizard.</CardDescription></CardHeader></Card><Card><CardHeader><CardTitle>3. Configure the webhook</CardTitle><CardDescription>In Meta Webhooks, subscribe to <code>messages</code>. Use your production callback URL and the same verification token saved in WhatsAI setup.</CardDescription></CardHeader></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-[#00a884]" />4. Test before going live</CardTitle><CardDescription>This checks the configured server credentials without exposing your access token.</CardDescription></CardHeader><CardContent><WhatsAppConnectionTest /></CardContent></Card></div>;
}
